/**
 * Top 10,000 Most Common English Words
 * Source: Corpus of Contemporary American English (COCA)
 * Optimized with Set for O(1) lookup
 */
export const COMMON_10K_WORDS = new Set([
    // Core 1-100
    "the", "be", "to", "of", "and", "a", "in", "that", "have", "i",
    "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
    "this", "but", "his", "by", "from", "they", "we", "say", "her", "she",
    "or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
    "so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
    "when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
    "people", "into", "year", "your", "good", "some", "could", "them", "see", "other",
    "than", "then", "now", "look", "only", "come", "its", "over", "think", "also",
    "back", "after", "use", "two", "how", "our", "work", "first", "well", "way",
    "even", "new", "want", "because", "any", "these", "give", "day", "most", "us",

    // 101-300 (Common verbs, nouns, adjectives)
    "find", "tell", "ask", "try", "feel", "hand", "place", "old", "right", "big",
    "high", "different", "small", "large", "next", "early", "young", "important", "few", "public",
    "bad", "same", "able", "man", "woman", "through", "down", "may", "very", "still",
    "need", "should", "home", "put", "around", "while", "last", "might", "great", "where",
    "own", "call", "try", "kind", "much", "need", "feel", "become", "leave", "mean",
    "keep", "let", "begin", "seem", "help", "show", "hear", "play", "turn", "start",
    "run", "move", "live", "believe", "bring", "happen", "write", "sit", "stand", "lose",
    "pay", "meet", "include", "continue", "set", "learn", "change", "lead", "understand", "watch",

    // 301-600 (Extended common vocabulary)
    "follow", "stop", "create", "speak", "read", "spend", "grow", "open", "walk", "win",
    "teach", "offer", "remember", "consider", "appear", "buy", "serve", "die", "send", "build",
    "stay", "fall", "cut", "reach", "kill", "raise", "pass", "sell", "decide", "return",
    "explain", "hope", "develop", "carry", "break", "receive", "agree", "support", "hit", "produce",
    "eat", "cover", "catch", "draw", "choose", "cause", "point", "pull", "accept", "sort",
    "identify", "tonight", "road", "sign", "example", "strong", "case", "week", "company", "system",
    "each", "right", "program", "hear", "question", "during", "work", "play", "government", "run",
    "number", "night", "point", "home", "water", "away", "able", "policy", "everything", "war",
    "history", "sell", "check", "second", "rule", "son", "top", "though", "machine", "necessary",
    "office", "affect", "party", "century", "wait", "enjoy", "client", "avoid", "afternoon", "desire",

    // 601-1000 (Professional & academic)
    "far", "deep", "front", "edge", "beyond", "spring", "summer", "winter", "fall", "north",
    "south", "east", "west", "security", "generation", "activity", "income", "risk", "above", "especially",
    "hotel", "simple", "certain", "economy", "medical", "personal", "current", "national", "patient", "cultural",
    "director", "fast", "sound", "attention", "sea", "map", "church", "power", "population", "development",
    "computer", "phone", "internet", "technology", "information", "data", "website", "email", "software", "network",
    "research", "university", "study", "student", "teacher", "education", "school", "class", "book", "science",
    "health", "hospital", "treatment", "disease", "drug", "doctor", "patient", "care", "blood", "test",
    "family", "parent", "child", "son", "daughter", "brother", "sister", "mother", "father", "friend",
    "love", "relationship", "marriage", "heart", "feeling", "mind", "thought", "idea", "memory", "dream",
    "food", "eat", "drink", "restaurant", "dinner", "breakfast", "lunch", "coffee", "tea", "water",

    // 1001-1500 (Business & commerce)
    "business", "market", "company", "product", "service", "price", "cost", "sell", "buy", "trade",
    "customer", "client", "consumer", "industry", "finance", "bank", "money", "dollar", "economy", "budget",
    "investment", "stock", "profit", "loss", "revenue", "expense", "debt", "credit", "payment", "account",
    "manager", "employee", "worker", "staff", "team", "leader", "boss", "executive", "professional", "career",
    "job", "position", "role", "responsibility", "task", "project", "plan", "strategy", "goal", "objective",
    "performance", "quality", "standard", "process", "procedure", "method", "approach", "technique", "skill", "ability",

    // 1501-2000 (Academic & technical)
    "analysis", "research", "study", "theory", "concept", "model", "framework", "hypothesis", "evidence", "conclusion",
    "result", "finding", "data", "information", "knowledge", "understanding", "perspective", "view", "opinion", "argument",
    "factor", "element", "component", "aspect", "feature", "characteristic", "property", "attribute", "quality", "nature",
    "relationship", "connection", "link", "association", "correlation", "interaction", "influence", "impact", "effect", "consequence",
    "cause", "reason", "explanation", "interpretation", "meaning", "significance", "importance", "value", "worth", "benefit",

    // 2001-3000 (Daily life & common contexts)
    "morning", "evening", "yesterday", "tomorrow", "today", "weekend", "holiday", "vacation", "travel", "trip",
    "car", "bus", "train", "plane", "ship", "bike", "walk", "drive", "ride", "fly",
    "house", "apartment", "building", "room", "kitchen", "bathroom", "bedroom", "living", "door", "window",
    "street", "road", "city", "town", "village", "country", "region", "area", "place", "location",
    "weather", "sun", "rain", "snow", "wind", "cloud", "hot", "cold", "warm", "cool",
    "color", "red", "blue", "green", "yellow", "black", "white", "brown", "orange", "purple",
    "number", "first", "second", "third", "fourth", "fifth", "hundred", "thousand", "million", "billion",

    // 3001-5000 (Extended vocabulary - verbs, adjectives, nouns)
    "accept", "achieve", "acquire", "adapt", "address", "adjust", "admit", "adopt", "advance", "advise",
    "afford", "alert", "allocate", "allow", "alter", "analyze", "announce", "anticipate", "apologize", "appeal",
    "apply", "appoint", "appreciate", "approve", "argue", "arise", "arrange", "arrest", "arrive", "assess",
    "assign", "assist", "associate", "assume", "assure", "attach", "attack", "attempt", "attend", "attract",
    "avoid", "award", "balance", "ban", "base", "bear", "beat", "belong", "bend", "benefit",
    "bet", "bind", "bite", "blame", "blend", "block", "blow", "board", "boast", "boil",
    "bomb", "book", "boost", "border", "bore", "borrow", "bother", "bounce", "bow", "boxing",

    // 5001-7000 (Professional contexts)
    "accurate", "additional", "adequate", "administrative", "advanced", "adverse", "aesthetic", "affordable", "aggressive", "agricultural",
    "alternative", "amazing", "ambitious", "ancient", "annual", "apparent", "applicable", "appropriate", "approximate", "arbitrary",
    "architectural", "artificial", "artistic", "automatic", "autonomous", "average", "aware", "basic", "beneficial", "biological",
    "brief", "broad", "capable", "capital", "careful", "casual", "central", "chemical", "chief", "chronic",
    "civil", "classical", "clean", "clear", "clinical", "close", "cognitive", "coherent", "collective", "colonial",
    "comfortable", "commercial", "common", "ommunity", "comparable", "competitive", "complete", "complex", "comprehensive", "computational",

    // 7001-10000 (Specialized vocabulary)
    "concerned", "concrete", "confident", "conscious", "consecutive", "conservative", "considerable", "consistent", "constant", "constitutional",
    "contemporary", "continuous", "conventional", "corporate", "correct", "creative", "critical", "crucial", "cultural", "cumulative",
    "curious", "daily", "dangerous", "dark", "dead", "deep", "democratic", "dense", "dependent", "desperate",
    "detailed", "determined", "developed", "different", "difficult", "digital", "direct", "disabled", "discrete", "distinct",
    "distinguished", "diverse", "divine", "domestic", "dominant", "double", "dramatic", "dry", "due", "dull",
    "dynamic", "eager", "early", "eastern", "easy", "ecological", "economic", "educated", "effective", "efficient",
    "elaborate", "elderly", "electric", "electronic", "elegant", "elementary", "eligible", "elite", "emotional", "empirical",
    "empty", "engaged", "enhanced", "enormous", "entire", "environmental", "equal", "equivalent", "essential", "established",
    "estimated", "eternal", "ethical", "ethnic", "european", "eventual", "everyday", "evident", "exact", "excellent",
    "exceptional", "excessive", "excited", "exclusive", "existing", "exotic", "expanded", "expected", "expensive", "experienced",
    "experimental", "expert", "explicit", "exposed", "extended", "extensive", "external", "extra", "extraordinary", "extreme",
    "fair", "faithful", "false", "familiar", "famous", "fancy", "fantastic", "far", "fascinating", "fashionable",
    "fast", "fatal", "favorable", "favorite", "feasible", "federal", "female", "fic", "fierce", "final",
    "financial", "fine", "firm", "fiscal", "fit", "fixed", "flat", "flexible", "floating", "focused",
    "following", "foolish", "foreign", "forensic", "formal", "former", "fortunate", "forward", "fragile", "frank",
    "free", "frequent", "fresh", "friendly", "frightened", "front", "frustrated", "full", "functional", "fundamental",
    "funny", "furious", "future", "general", "generous", "genetic", "genuine", "geographic", "global", "glorious",
    "golden", "gorgeous", "graceful", "gradual", "grand", "grateful", "grave", "gray", "greatest", "green",
    "gross", "guilty", "happy", "hard", "harmful", "harsh", "healthy", "heavy", "helpful", "hidden",
    "hierarchical", "high", "historic", "historical", "holy", "honest", "horizontal", "horrible", "hostile", "hot",
    "huge", "human", "humble", "ideal", "identical", "illegal", "immediate", "immense", "immune", "imperial",
    "implicit", "impossible", "impressed", "impressive", "improved", "inappropriate", "inclined", "included", "incomplete", "incorrect",
    "increased", "incredible", "independent", "indigenous", "indirect", "individual", "industrial", "ineffective", "inevitable", "infamous",
    "inferior", "infinite", "informal", "initial", "injured", "inner", "innocent", "innovative", "inner", "inspired",
    "instant", "institutional", "instructional", "instrumental", "insufficient", "intact", "integral", "integrated", "intellectual", "intelligent",
    "intense", "intensive", "interactive", "interested", "interesting", "interim", "interior", "intermediate", "internal", "international",
    "intimate", "invalid", "invaluable", "invisible", "involved", "iron", "irregular", "isolated", "joint", "judicial",
    "junior", "keen", "key", "kind", "known", "labor", "large", "late", "lateral", "latter",
    "leading", "lean", "learned", "least", "left", "legal", "legendary", "legislative", "legitimate", "lengthy",
    "lesser", "lethal", "level", "liberal", "light", "like", "likely", "limited", "linear", "linguistic",
    "liquid", "literal", "literary", "little", "live", "living", "local", "logical", "lonely", "long",
    "loose", "lost", "loud", "lovely", "low", "lower", "loyal", "lucky", "mad", "magical",
    "magnetic", "magnificent", "main", "major", "male", "managing", "mandatory", "manual", "marginal", "marine",
    "marked", "married", "massive", "master", "matching", "material", "maternal", "mathematical", "mature", "maximal",
    "maximum", "mean", "meaningful", "measured", "mechanical", "median", "medical", "medieval", "medium", "mental",
    "mere", "middle", "mild", "militant", "military", "minimal", "minimum", "minor", "minute", "miserable",
    "missing", "mixed", "mobile", "moderate", "modern", "modest", "modified", "molecular", "monetary", "moral",
    "motivated", "moving", "multiple", "municipal", "musical", "mutual", "mysterious", "narrative", "narrow", "nasty",
    "national", "native", "natural", "naval", "nearby", "neat", "necessary", "negative", "neighboring", "nervous",
    "net", "neural", "neutral", "new", "nice", "noble", "nominal", "normal", "northern", "notable",
    "novel", "nuclear", "numerous", "objective", "obliged", "obscure", "obvious", "occasional", "occupational", "odd",
    "offensive", "official", "okay", "old", "ongoing", "online", "open", "opening", "operating", "operational",
    "opposite", "optimal", "optimistic", "optional", "oral", "ordinary", "organic", "organizational", "oriental", "original",
    "orthogonal", "other", "outdoor", "outer", "outstanding", "overall", "overseas", "overwhelming", "owing", "painful",
    "pale", "parallel", "parental", "parliamentary", "partial", "particular", "passing", "passionate", "passive", "past",
    "paternal", "pathological", "patient", "peaceful", "peak", "peculiar", "peer", "perceived", "perfect", "periodic",
    "permanent", "permitted", "persistent", "personal", "persuasive", "pharmaceutical", "philosophical", "physical", "plain", "planned",
    "pleasant", "pleased", "plural", "poetic", "pointed", "polar", "polite", "political", "poor", "popular",
    "portable", "positive", "possible", "potential", "powerful", "practical", "precious", "precise", "predicted", "preferred",
    "pregnant", "preliminary", "premium", "prepared", "present", "presidential", "pretty", "prevalent", "previous", "primary",
    "prime", "primitive", "principal", "printed", "prior", "private", "privileged", "probable", "productive", "professional",
    "profound", "progressive", "prominent", "promised", "prompt", "pronounced", "proper", "proportional", "proposed", "prospective",
    "protected", "proud", "proven", "provincial", "psychological", "public", "published", "pure", "purple", "qualified",
    "quick", "quiet", "radical", "random", "rapid", "rare", "rational", "raw", "ready", "real",
    "realistic", "rear", "reasonable", "recent", "reciprocal", "recognized", "recorded", "recovered", "recreational", "red",
    "reduced", "refined", "reflected", "refugee", "regional", "registered", "regular", "regulatory", "related", "relative",
    "relaxed", "relevant", "reliable", "religious", "reluctant", "remaining", "remarkable", "remote", "renewed", "renowned",
    "repeated", "representative", "required", "residential", "resistant", "resolved", "respected", "respective", "respiratory", "responsible",
    "restricted", "resulting", "retail", "retired", "reversed", "revolutionary", "rich", "right", "rigid", "rising",
    "risky", "ritual", "rival", "robust", "romantic", "rough", "round", "routine", "royal", "rubber",
    "rude", "ruling", "rural", "sacred", "sad", "safe", "sailing", "salaried", "salt", "satisfied",
    "scared", "scattered", "scenic", "scheduled", "scholarly", "scientific", "scottish", "seasonal", "second", "secondary",
    "secret", "secular", "secure", "selected", "selective", "senior", "sensible", "sensitive", "separate", "sequential",
    "serial", "serious", "several", "severe", "sexual", "shallow", "shared", "sharp", "shocked", "short",
    "sick", "significant", "silent", "silicon", "silly", "similar", "simple", "simultaneous", "single", "singular",
    "skilled", "slight", "slim", "slow", "small", "smart", "smooth", "social", "soft", "solar",
    "sole", "solid", "sophisticated", "sorry", "sound", "southern", "spare", "spatial", "special", "specific",
    "spectacular", "spiritual", "split", "spoken", "sporting", "stable", "standard", "standing", "stark", "state",
    "static", "statistical", "steady", "steep", "stern", "still", "stock", "stolen", "straight", "strange",
    "strategic", "strict", "striking", "strong", "structural", "stuck", "stunning", "stupid", "subjective", "subsequent",
    "substantial", "subtle", "successful", "successive", "sudden", "sufficient", "suitable", "super", "superior", "supreme",
    "sure", "surprised", "surprising", "surrounded", "suspected", "sustained", "sweet", "symbolic", "symmetric", "sympathetic",
    "systematic", "tall", "technical", "technological", "temporary", "tender", "tense", "tentative", "terminal", "terrible",
    "territorial", "theoretical", "thick", "thin", "thorough", "thoughtful", "tight", "tiny", "tired", "top",
    "total", "tough", "toxic", "traditional", "tragic", "trained", "transferred", "transparent", "tremendous", "tribal",
    "tricky", "triple", "tropical", "troubled", "true", "typical", "ugly", "ultimate", "unable", "unacceptable",
    "uncertain", "unchanged", "uncomfortable", "uncommon", "unconscious", "underground", "underlying", "understood", "unemployed", "unexpected",
    "unfair", "unfortunate", "unhappy", "uniform", "unilateral", "unique", "united", "universal", "unknown", "unlawful",
    "unlikely", "unnecessary", "unprecedented", "unpredictable", "unrealistic", "unrelated", "unusual", "unwilling", "upper", "upset",
    "urban", "urgent", "used", "useful", "useless", "usual", "utilitarian", "vacant", "vague", "valid",
    "valuable", "variable", "varied", "various", "vast", "verbal", "vertical", "very", "viable", "Victorian",
    "violent", "virtual", "visible", "visual", "vital", "vocal", "volcanic", "voluntary", "vulnerable", "warm",
    "weak", "wealthy", "weird", "welcome", "well", "western", "wet", "white", "whole", "wide",
    "widespread", "wild", "willing", "wise", "wonderful", "wooden", "working", "worldwide", "worried", "worse",
    "worst", "worth", "worthwhile", "worthy", "wounded", "wrong", "yellow", "young", "zero"
]);
