import { AIIsm } from "../types";

export const SHITLIST: AIIsm[] = [
    {
        id: "delve",
        word: "delve",
        reason: "The #1 AI giveaway. Humans say 'dig into' or 'explore'.",
        alternatives: ["dig into", "explore", "investigate"],
        category: "Deep Silicon",
    },
    {
        id: "tapestry",
        word: "tapestry",
        reason: "Overly poetic filler used to link unrelated concepts.",
        alternatives: ["mix", "range", "collection"],
        category: "Deep Silicon",
    },
    {
        id: "nuanced",
        word: "nuanced",
        reason: "Often used to sound smart without adding detail.",
        alternatives: ["subtle", "complex", "detailed"],
        category: "Deep Silicon",
    },
    {
        id: "underscore",
        word: "underscore",
        reason: "Robotic transition.",
        alternatives: ["highlight", "emphasize", "prove"],
        category: "Generic",
    },
    {
        id: "testament",
        word: "testament",
        reason: "Cliche structure: 'It is a testament to...'",
        alternatives: ["proof", "evidence", "sign"],
        category: "Deep Silicon",
    },
    {
        id: "landscape",
        word: "landscape",
        reason: "Usually 'ever-evolving landscape'.",
        alternatives: ["field", "world", "industry"],
        category: "Generic",
    },
    {
        id: "game-changer",
        word: "game-changer",
        reason: "Marketing fluff.",
        alternatives: ["major shift", "breakthrough", "big deal"],
        category: "Generic",
    },
    {
        id: "realm",
        word: "realm",
        reason: "Unnecessarily fantasy-coded.",
        alternatives: ["area", "field", "zone"],
        category: "Deep Silicon",
    },
    {
        id: "foster",
        word: "foster",
        reason: "Corporate-speak for 'encourage'.",
        alternatives: ["build", "grow", "encourage"],
        category: "Generic",
    },
    {
        id: "democratize",
        word: "democratize",
        reason: "Overused tech buzzword.",
        alternatives: ["make accessible", "open up"],
        category: "Deep Silicon",
    },
    {
        id: "harness",
        word: "harness",
        reason: "Robotic verb.",
        alternatives: ["use", "utilize", "control"],
        category: "Generic",
    },
    {
        id: "comprehensive",
        word: "comprehensive",
        reason: "Standard report filler.",
        alternatives: ["complete", "full", "thorough"],
        category: "Generic",
    },
    {
        id: "plethora",
        word: "plethora",
        reason: "Fancy for 'a lot'.",
        alternatives: ["many", "tons of", "a lot"],
        category: "Deep Silicon",
    },
    {
        id: "multifaceted",
        word: "multifaceted",
        reason: "Wordy.",
        alternatives: ["complex", "varied"],
        category: "Generic",
    },
    {
        id: "pivotal",
        word: "pivotal",
        reason: "Dramatic linking word.",
        alternatives: ["key", "crucial", "huge"],
        category: "Generic",
    },
    {
        id: "unleash",
        word: "unleash",
        reason: "Hype language.",
        alternatives: ["release", "start", "unlock"],
        category: "Generic",
    },
    {
        id: "navigating",
        word: "navigating",
        reason: "Often 'navigating the landscape'.",
        alternatives: ["handling", "maneuvering"],
        category: "Generic",
    },
    {
        id: "rich",
        word: "rich",
        reason: "Usually 'rich history' or 'rich tapestry'.",
        alternatives: ["deep", "full"],
        category: "Generic",
    },
    {
        id: "intertwined",
        word: "intertwined",
        reason: "Complex connector.",
        alternatives: ["linked", "connected"],
        category: "Deep Silicon",
    },
    {
        id: "symphony",
        word: "symphony",
        reason: "Poetic metaphor for systems.",
        alternatives: ["blend", "mix"],
        category: "Deep Silicon",
    },
    {
        id: "beacon",
        word: "beacon",
        reason: "'Beacon of hope'.",
        alternatives: ["sign", "guide"],
        category: "Deep Silicon",
    },
    {
        id: "crucible",
        word: "crucible",
        reason: "Drama overload.",
        alternatives: ["test", "challenge"],
        category: "Deep Silicon",
    },
    {
        id: "leverage",
        word: "leverage",
        reason: "Corporate classic.",
        alternatives: ["use", "take advantage of"],
        category: "Generic",
    },
    {
        id: "poised",
        word: "poised",
        reason: "'Poised to revolutionize'.",
        alternatives: ["ready", "set"],
        category: "Generic",
    },
    {
        id: "unwavering",
        word: "unwavering",
        reason: "'Unwavering commitment'.",
        alternatives: ["strong", "steady"],
        category: "Deep Silicon",
    },
    {
        id: "paramount",
        word: "paramount",
        reason: "Old-school formal.",
        alternatives: ["critical", "key", "vital"],
        category: "Generic",
    },
    {
        id: "paradigm",
        word: "paradigm",
        reason: "'Paradigm shift'.",
        alternatives: ["model", "way"],
        category: "Deep Silicon",
    },
    {
        id: "seamless",
        word: "seamless",
        reason: "Tech favorite.",
        alternatives: ["smooth", "easy"],
        category: "Generic",
    },
    {
        id: "meticulous",
        word: "meticulous",
        reason: "Over-descriptive.",
        alternatives: ["careful", "detailed"],
        category: "Generic",
    },
    {
        id: "transformative",
        word: "transformative",
        reason: "Hype.",
        alternatives: ["big", "major"],
        category: "Generic",
    },
];
